<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>PBRReferenceForge</AssemblyName>
    <RootNamespace>TextureCreator.App</RootNamespace>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\TextureCreator.Core\TextureCreator.Core.csproj" /></ItemGroup>
</Project>
